import { BaseLayout } from '@layouts/BaseLayout';
import Footer from '@shared-components/Footer/Footer';
import Header from '@shared-components/Header/Header';
import Newsletter from '@shared-components/Newsletter/Newsletter';
import "./globals.css";

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body suppressHydrationWarning className='main-layout'>

				<Header />
				{children}
				<Newsletter />
				<Footer />

			</body>
		</html>
	);
}
