import { Footer, Header, Newsletter } from '@shared-components';
import '@styles/globals.sass';
import '@styles/color.sass';

export const metadata = {
	title: {
		template: '%s - SMART LOYALTY',
		default: 'SMART LOYALTY - Giải pháp khách hàng trung thành Loyalty'
	},
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (

		<html lang='en'>
			<body suppressHydrationWarning className='main-layout'>
				<Header />
				{children}
				<Newsletter />
				<Footer />
			</body>
		</html>
	);
}
